### ISSUE TITLE
Re-implement logging in clovertone

### ISSUE THREAD

**Issue by lmcmicu** [jamesaoverton/clovertonemusic#10]
One of the libraries being used in clovertone has been withdrawn, i.e., the clj-logging-config library. Apparently it depends on log4j 1.2 which is end-of-line and has known security vulnerabilities. See: https://github.com/malcolmsparks/clj-logging-config

We need to re-implement logging in a way that does not use this library.

**Comment by jamesaoverton** [comment]
I don't have a suggestion for a replacement. This is the first place I look when I need a Clojure library:  https://www.clojure-toolbox.com

**Comment by lmcmicu** [comment]
I was probably just going to write a custom function. I don't think we need advanced logging functionality for clovertone.

**Comment by jamesaoverton** [comment]
Sound good!
