### ISSUE TITLE
Upgrade clovertone dependencies

### ISSUE THREAD

**Issue by lmcmicu** [jamesaoverton/clovertonemusic#11]
A few of the dependencies have been upgraded since the project.clj file was first set up. SInce the new server has not been deployed yet, now is a good time to go through the dependencies to see what can be upgraded.

**Comment by jamesaoverton** [comment]
Probably overkill for the current purpose, but I thought I'd mention the [lein-ancient](https://github.com/xsc/lein-ancient) plugin, which reports on new versions of dependencies.
