### ISSUE TITLE
Consider system for manually adding purchases

### ISSUE THREAD

**Issue by jamesaoverton** [jamesaoverton/clovertonemusic#18]
Please assess the difficulty of having an admin manually add a purchase for an existing user, including recording the purchase to the Google Sheet, stamping the charts, and including the purchase on the user's account page.

**Comment by lmcmicu** [comment]
It might be worth writing a script that will output step-by-step instructions for how to do this in a given case.

**Comment by jamesaoverton** [comment]
Please consider this option: Add yet another special admin to the `config.edn`, pointing to an existing user entry. That admin user logs in and adds items to his cart as usual. At checkout, he is asked for the email address of another user (who must already be in the system, because we'll need their info for stamping). Then the payment step is skipped, and the purchase is marked as complete. (Maybe we should note that this used the manual system, not a normal purchase). Then stamping works as usual. The admin needs to see the purchase URL that he can then email to the customer. the
